### ISSUE TITLE
Vaccinations scraper data not updated

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/netherlands-vaccinations-scraper#1]
Hi,

I noticed that the data is not updated today.

And I am not sure but the structure data["vaccinaties"]["data"]['kpi_total']['tab_total_estimated']['value'] may have changed? (data["vaccinaties"]["data"] does not exist?)

I tried to walk the structure but have no idea where else to get the data from, I cannot find the actual data within data["vaccinaties"] and not other 'vaccinaties' among all of the keys in data... 

Kind regards, Wouter

**Comment by Sikerdebaard** [comment]
Yup, the dashboard has changed formats. The new data is now in this file https://github.com/Sikerdebaard/netherlands-vaccinations-scraper/blob/main/vaccine_administered_total.csv

Alternatively you can pull the data from the dashboard's JSON directly  
https://coronadashboard.rijksoverheid.nl/json/NL.json

`vaccine_administered_total` or any of the `vaccine_administered_*` keys for specific instances.

**Comment by wbijster** [comment]
Many thanks once again!! Somehow the date seems to be one day off: the max date as reported below the data at the [dashboard](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties) is currently the 19th ("Waarde van vrijdag 19 februari" ) and it is the 18th in the CSV (but the values for reported and estimated vaccinations are in sink with the latest values at the dashboard). It is probably wrong in the source json but I did not convert the Unix date myself (sorry, I also notice the text "Laatste waardes verkregen op donderdag 18 februari. " somewhere else at the dashboard).

**Comment by Sikerdebaard** [comment]
There's two different ways to look at the dashboard data. Technically the doses administered describes the value of the previous day. But the dashboard shows a date on when the number was published as well. This shifts everything by one day. Does that make sense?

**Comment by wbijster** [comment]
Yes, I understand. I guess that they changed the date reported with the data while moving the data to the json. It felt like loosing a day but it is the same thing. I now processed the Unix dates btw, using the pd.to_datetime with unit='s', I did not expect that it would be that easy to process the data, many thanks for the example!
